# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/eth_ref_clk.xdc

# Block Designs: bd/echo_setup/echo_setup.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==echo_setup || ORIG_REF_NAME==echo_setup} -quiet] -quiet

# IP: bd/echo_setup/ip/echo_setup_microblaze_0_0/echo_setup_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==echo_setup_microblaze_0_0 || ORIG_REF_NAME==echo_setup_microblaze_0_0} -quiet] -quiet

# IP: bd/echo_setup/ip/echo_setup_dlmb_v10_0/echo_setup_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==echo_setup_dlmb_v10_0 || ORIG_REF_NAME==echo_setup_dlmb_v10_0} -quiet] -quiet

# IP: bd/echo_setup/ip/echo_setup_ilmb_v10_0/echo_setup_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==echo_setup_ilmb_v10_0 || ORIG_REF_NAME==echo_setup_ilmb_v10_0} -quiet] -quiet

# IP: bd/echo_setup/ip/echo_setup_dlmb_bram_if_cntlr_0/echo_setup_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==echo_setup_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==echo_setup_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/echo_setup/ip/echo_setup_ilmb_bram_if_cntlr_0/echo_setup_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==echo_setup_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==echo_setup_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/echo_setup/ip/echo_setup_lmb_bram_0/echo_setup_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==echo_setup_lmb_bram_0 || ORIG_REF_NAME==echo_setup_lmb_bram_0} -quiet] -quiet

# IP: bd/echo_setup/ip/echo_setup_xbar_0/echo_setup_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==echo_setup_xbar_0 || ORIG_REF_NAME==echo_setup_xbar_0} -quiet] -quiet

# IP: bd/echo_setup/ip/echo_setup_microblaze_0_axi_periph_0/echo_setup_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==echo_setup_microblaze_0_axi_periph_0 || ORIG_REF_NAME==echo_setup_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/echo_setup/ip/echo_setup_microblaze_0_axi_intc_0/echo_setup_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==echo_setup_microblaze_0_axi_intc_0 || ORIG_REF_NAME==echo_setup_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/echo_setup/ip/echo_setup_microblaze_0_xlconcat_0/echo_setup_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==echo_setup_microblaze_0_xlconcat_0 || ORIG_REF_NAME==echo_setup_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/echo_setup/ip/echo_setup_mdm_1_0/echo_setup_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==echo_setup_mdm_1_0 || ORIG_REF_NAME==echo_setup_mdm_1_0} -quiet] -quiet

# IP: bd/echo_setup/ip/echo_setup_clk_wiz_1_0/echo_setup_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==echo_setup_clk_wiz_1_0 || ORIG_REF_NAME==echo_setup_clk_wiz_1_0} -quiet] -quiet

# IP: bd/echo_setup/ip/echo_setup_rst_clk_wiz_1_100M_0/echo_setup_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==echo_setup_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==echo_setup_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/echo_setup/ip/echo_setup_mii_to_rmii_0_0/echo_setup_mii_to_rmii_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==echo_setup_mii_to_rmii_0_0 || ORIG_REF_NAME==echo_setup_mii_to_rmii_0_0} -quiet] -quiet

# IP: bd/echo_setup/ip/echo_setup_axi_uartlite_0_0/echo_setup_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==echo_setup_axi_uartlite_0_0 || ORIG_REF_NAME==echo_setup_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/echo_setup/ip/echo_setup_axi_ethernetlite_0_0/echo_setup_axi_ethernetlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==echo_setup_axi_ethernetlite_0_0 || ORIG_REF_NAME==echo_setup_axi_ethernetlite_0_0} -quiet] -quiet

# IP: bd/echo_setup/ip/echo_setup_axi_timer_0_0/echo_setup_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==echo_setup_axi_timer_0_0 || ORIG_REF_NAME==echo_setup_axi_timer_0_0} -quiet] -quiet

# IP: bd/echo_setup/ip/echo_setup_mig_7series_0_0/echo_setup_mig_7series_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==echo_setup_mig_7series_0_0 || ORIG_REF_NAME==echo_setup_mig_7series_0_0} -quiet] -quiet

# IP: bd/echo_setup/ip/echo_setup_axi_smc_0/echo_setup_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==echo_setup_axi_smc_0 || ORIG_REF_NAME==echo_setup_axi_smc_0} -quiet] -quiet

# IP: bd/echo_setup/ip/echo_setup_rst_mig_7series_0_81M_0/echo_setup_rst_mig_7series_0_81M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==echo_setup_rst_mig_7series_0_81M_0 || ORIG_REF_NAME==echo_setup_rst_mig_7series_0_81M_0} -quiet] -quiet

# XDC: /home/jack/VERILOG/4_29_onward/echo_attempt7/echo_setup/echo_setup.gen/sources_1/bd/echo_setup/echo_setup_ooc.xdc
